apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres-datasource
    access: proxy
    url: db:5432
    user: admin
    secureJsonData:
      password: password
    jsonData:
      database: edtech_db
      sslmode: disable
      postgresVersion: 1300
      timescaledb: false
    isDefault: true
    editable: true

